spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        show_sql: true

  flyway:
    enabled: true

springdoc:
  swagger-ui:
    # config-url: /v3/api-docs/swagger-config
    path: /swagger
    url: /v3/api-docs
    operations-sorter: method
  api-docs:
    enabled: true
    path: /v3/api-docs

server:
  # forward-headers-strategy: framework
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
