

services:
  seas-spring:
    build:
      context: ../
      dockerfile: "./docker/dockerfile/spring.dockerfile"
    ports:
      - 8080:8080
    networks:
      - backend

  seas-redis:
    image: redis
    ports:
      - 6379:6379
    build:
      context: ../
    networks:
      - backend

  seas-mysql:
    build:
      context: ../
      dockerfile: "./docker/dockerfile/mysql.dockerfile"
    env_file: ".env"
    ports:
      - 3306:3306
    networks:
      - backend

networks:
  backend:
    external: true